# Generated by Django 4.0.3 on 2022-11-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsForm',
            new_name='ContactUs',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='number',
            new_name='phone',
        ),
    ]
