# Generated by Django 4.0.3 on 2022-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_rename_contactusform_contactus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='شماره تلفن'),
        ),
    ]
