# Generated by Django 4.0.3 on 2022-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555, verbose_name='موضوع')),
                ('little_discription', models.CharField(max_length=555, verbose_name='توضیحات جزعی')),
                ('discription', models.TextField(null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'درباره',
                'verbose_name_plural': 'درباره',
            },
        ),
    ]
