# Generated by Django 4.0.3 on 2022-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='number'),
        ),
    ]
