# Generated by Django 4.0.3 on 2022-09-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='پست الکترونیک'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=12, verbose_name='شماره تلفن'),
        ),
    ]
