# Generated by Django 4.0.3 on 2022-09-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='پست الکترونیک'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=12, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
