# Generated by Django 4.0.3 on 2022-09-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=12, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('code', models.SmallIntegerField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'کد:otp',
                'verbose_name_plural': 'کد:otp ها',
            },
        ),
    ]
