# Generated by Django 4.0.3 on 2022-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True, verbose_name='قیمت تخفیف خورده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_for_show',
            field=models.CharField(max_length=100, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(null=True, verbose_name='تعداد بازدید پست'),
        ),
    ]
