# Generated by Django 4.0.3 on 2022-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image', verbose_name='عکس کالا'),
        ),
    ]
