# Generated by Django 4.0.3 on 2022-10-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_poster_image_alter_poster_title_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
