# Generated by Django 4.0.3 on 2022-10-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_hits_delete_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس ای پی')),
            ],
            options={
                'verbose_name': 'ای پی',
                'verbose_name_plural': 'ادرس ای پی',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blog.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
