# Generated by Django 4.0.3 on 2022-10-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ipaddress_post_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_for_show',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
