# Generated by Django 4.0.3 on 2022-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_title_for_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='important_title',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کالا به اینگلیسی'),
        ),
    ]
