# Generated by Django 4.0.3 on 2022-10-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_important_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discription',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
