# Generated by Django 4.0.3 on 2022-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_discription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'پست', 'verbose_name_plural': 'ایجاد پست جدید'},
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='قیمت تخفیف خورده'),
        ),
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blog.ipaddress', verbose_name='بازدید ها'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image', verbose_name='عکس کالا'),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True, verbose_name='قیمت اصلی'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(null=True, verbose_name='تعداد بازدید پست'),
        ),
    ]
