# Generated by Django 4.0.3 on 2022-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_options_post_created_post_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
