# Generated by Django 4.0.3 on 2022-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comments_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته بندی ها')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_for_shows', models.CharField(max_length=100, null=True, verbose_name='نام کالا')),
                ('important_titles', models.CharField(max_length=100, null=True, verbose_name='نام کالا به اینگلیسی')),
                ('discriptions', models.TextField(null=True, verbose_name='توضیحات')),
                ('discounts', models.IntegerField(null=True, verbose_name='قیمت تخفیف خورده')),
                ('prices', models.IntegerField(null=True, verbose_name='قیمت اصلی')),
                ('images', models.ImageField(null=True, upload_to='shop_image', verbose_name='عکس کالا')),
                ('slugs', models.SlugField(blank=True, null=True)),
                ('createds', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(related_name='shops', to='blog.shopcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'ایجاد پست برای فروش',
                'ordering': ('-createds',),
            },
        ),
    ]
