# Generated by Django 4.0.3 on 2022-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_shopcategory_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sellerinfo',
            field=models.BooleanField(default=False, verbose_name='قابل فروش'),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
