# Generated by Django 4.0.3 on 2023-01-10 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان های همگانی',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(verbose_name='متن اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='انتخاب کاربر'),
        ),
    ]
